// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6fuCXUw0I3NLxXxe24yYGyhxdBvz-R8k',
    appId: '1:670051743143:web:de24efacfd54de34f2f282',
    messagingSenderId: '670051743143',
    projectId: 'estegatha-notification',
    authDomain: 'estegatha-notification.firebaseapp.com',
    storageBucket: 'estegatha-notification.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAi2XluzSbTa9_F-9IzAOv3QoIO9mL4vc',
    appId: '1:670051743143:android:04f87ed1fd48d985f2f282',
    messagingSenderId: '670051743143',
    projectId: 'estegatha-notification',
    storageBucket: 'estegatha-notification.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBLR8SFLHeNGtPYXBnYXrGuSV5JqbuEYg',
    appId: '1:670051743143:ios:9b468b8f837082f0f2f282',
    messagingSenderId: '670051743143',
    projectId: 'estegatha-notification',
    storageBucket: 'estegatha-notification.appspot.com',
    iosBundleId: 'com.example.estegatha',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBLR8SFLHeNGtPYXBnYXrGuSV5JqbuEYg',
    appId: '1:670051743143:ios:9b468b8f837082f0f2f282',
    messagingSenderId: '670051743143',
    projectId: 'estegatha-notification',
    storageBucket: 'estegatha-notification.appspot.com',
    iosBundleId: 'com.example.estegatha',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB6fuCXUw0I3NLxXxe24yYGyhxdBvz-R8k',
    appId: '1:670051743143:web:adb7c5c6d108bb65f2f282',
    messagingSenderId: '670051743143',
    projectId: 'estegatha-notification',
    authDomain: 'estegatha-notification.firebaseapp.com',
    storageBucket: 'estegatha-notification.appspot.com',
  );

}